# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "overlay" "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "loop" "overlay" ];
  boot.kernelModules = [ "kvm-intel" "loop" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
      options = [ "mode=0755" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/09ec36e4-117e-49cf-9bbb-f2b1a0215d71";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.etc-lower" =
    { device = "/dev/disk/by-uuid/09ec36e4-117e-49cf-9bbb-f2b1a0215d71";
      fsType = "btrfs";
      neededForBoot = true;
      options = [
        "loop"
        "subvol=ETC"
      ];
    };

  fileSystems."/.home-lower" =
    { device = "/dev/disk/by-uuid/09ec36e4-117e-49cf-9bbb-f2b1a0215d71";
      fsType = "btrfs";
      neededForBoot = true;
      options = [
        "loop"
        "subvol=HOME"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/00C2-275C";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "overlay2";
      fsType = "overlay";
      neededForBoot = true;
      depends = [
        "/.home-lower"
        "/.home-upper"
        "/.home-work"
      ];
     options = [
        "lowerdir=/.home-lower"
        "upperdir=/.home-upper"
        "workdir=/.home-work"
     ];
    };

  fileSystems."/etc" =
    { device = "overlay";
      fsType = "overlay";
      depends = [
        "/.etc-lower"
        "/.etc-upper"
        "/.etc-work"
      ];
     options = [
        "lowerdir=/.etc-lower"
        "upperdir=/.etc-upper"
        "workdir=/.etc-work"
     ];
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
